-- This module depends on the installed native ontology and LLM schema validator.
BEGIN;
CREATE SCHEMA IF NOT EXISTS editorial;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS editorial.contract(version text PRIMARY KEY, schema jsonb NOT NULL, content_hash text NOT NULL);
INSERT INTO editorial.contract SELECT 'hop-product-occupations-v1',s,ontology.hash(s)
FROM (SELECT $contract${"type":"object","properties":{"schema_version":{"type":"string","minLength":1,"maxLength":4000,"enum":["hop-product-occupations-v1"]},"source_id":{"type":"string","minLength":1,"maxLength":4000,"enum":["INTERNAL_EDITORIAL"]},"catalogue_id":{"type":"string","minLength":1,"maxLength":4000,"enum":["product-occupations"]},"catalogue_version":{"type":"integer","minimum":1,"maximum":2147483647},"actor":{"type":"string","minLength":1,"maxLength":200},"actor_kind":{"type":"string","minLength":1,"maxLength":4000,"enum":["human","assistant"]},"scheme":{"type":"object","properties":{"code":{"type":"string","minLength":1,"maxLength":4000,"enum":["product-occupations"]},"name":{"type":"string","minLength":1,"maxLength":200},"description":{"type":"string","minLength":1,"maxLength":4000}},"required":["code","name","description"],"additionalProperties":false},"occupations":{"type":"array","minItems":4,"maxItems":4,"items":{"type":"object","properties":{"code":{"type":"string","minLength":1,"maxLength":4000,"enum":["AI_ENGINEER","BACKEND_DEVELOPER","FRONTEND_DEVELOPER","DATA_ANALYST"]},"name":{"type":"string","minLength":1,"maxLength":200},"description":{"type":"string","minLength":1,"maxLength":4000},"aliases":{"type":"array","maxItems":30,"items":{"type":"string","minLength":1,"maxLength":200}},"boundary_notes":{"type":"array","minItems":1,"maxItems":20,"items":{"type":"string","minLength":1,"maxLength":4000}}},"required":["code","name","description","aliases","boundary_notes"],"additionalProperties":false}}},"required":["schema_version","source_id","catalogue_id","catalogue_version","actor","actor_kind","scheme","occupations"],"additionalProperties":false}$contract$::jsonb s) v ON CONFLICT DO NOTHING;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM editorial.contract WHERE version='hop-product-occupations-v1'
  AND schema=$contract${"type":"object","properties":{"schema_version":{"type":"string","minLength":1,"maxLength":4000,"enum":["hop-product-occupations-v1"]},"source_id":{"type":"string","minLength":1,"maxLength":4000,"enum":["INTERNAL_EDITORIAL"]},"catalogue_id":{"type":"string","minLength":1,"maxLength":4000,"enum":["product-occupations"]},"catalogue_version":{"type":"integer","minimum":1,"maximum":2147483647},"actor":{"type":"string","minLength":1,"maxLength":200},"actor_kind":{"type":"string","minLength":1,"maxLength":4000,"enum":["human","assistant"]},"scheme":{"type":"object","properties":{"code":{"type":"string","minLength":1,"maxLength":4000,"enum":["product-occupations"]},"name":{"type":"string","minLength":1,"maxLength":200},"description":{"type":"string","minLength":1,"maxLength":4000}},"required":["code","name","description"],"additionalProperties":false},"occupations":{"type":"array","minItems":4,"maxItems":4,"items":{"type":"object","properties":{"code":{"type":"string","minLength":1,"maxLength":4000,"enum":["AI_ENGINEER","BACKEND_DEVELOPER","FRONTEND_DEVELOPER","DATA_ANALYST"]},"name":{"type":"string","minLength":1,"maxLength":200},"description":{"type":"string","minLength":1,"maxLength":4000},"aliases":{"type":"array","maxItems":30,"items":{"type":"string","minLength":1,"maxLength":200}},"boundary_notes":{"type":"array","minItems":1,"maxItems":20,"items":{"type":"string","minLength":1,"maxLength":4000}}},"required":["code","name","description","aliases","boundary_notes"],"additionalProperties":false}}},"required":["schema_version","source_id","catalogue_id","catalogue_version","actor","actor_kind","scheme","occupations"],"additionalProperties":false}$contract$::jsonb AND content_hash=ontology.hash(schema))
 THEN RAISE EXCEPTION 'EDITORIAL_CONTRACT_CHANGED'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='editorial_contract_immutable' AND tgrelid='editorial.contract'::regclass) THEN
  CREATE TRIGGER editorial_contract_immutable BEFORE UPDATE OR DELETE ON editorial.contract
  FOR EACH ROW EXECUTE FUNCTION ontology.immutable();
 END IF;
END $$;
COMMIT;
