BEGIN;
CREATE TABLE IF NOT EXISTS ontology.duplicate_contract(version text PRIMARY KEY,schema jsonb NOT NULL,content_hash text NOT NULL);
INSERT INTO ontology.duplicate_contract SELECT 'hop-duplicate-proposal-v1',s,ontology.hash(s)
FROM (SELECT $schema${"type":"object","properties":{"schema_version":{"type":"string","minLength":1,"maxLength":8000,"enum":["hop-duplicate-proposal-v1"]},"release_id":{"type":"string","minLength":1,"maxLength":8000},"cluster_id":{"type":"string","minLength":1,"maxLength":8000},"parent_id":{"type":["string","null"],"minLength":1,"maxLength":8000},"member_ids":{"type":"array","minItems":2,"maxItems":1000,"items":{"type":"string","minLength":1,"maxLength":8000}},"source_binding_hash":{"type":"string","minLength":1,"maxLength":8000},"actor":{"type":"string","minLength":1,"maxLength":8000},"actor_kind":{"type":"string","minLength":1,"maxLength":8000,"enum":["human","assistant"]},"method":{"type":"string","minLength":1,"maxLength":8000,"enum":["MANUAL","MODEL_INFERRED"]},"model_id":{"type":["string","null"],"minLength":1,"maxLength":8000},"prompt_version":{"type":["string","null"],"minLength":1,"maxLength":8000},"resolver_version":{"type":"string","minLength":1,"maxLength":8000},"reason":{"type":"string","minLength":1,"maxLength":8000}},"required":["schema_version","release_id","cluster_id","parent_id","member_ids","source_binding_hash","actor","actor_kind","method","model_id","prompt_version","resolver_version","reason"],"additionalProperties":false}$schema$::jsonb s) x ON CONFLICT DO NOTHING;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM ontology.duplicate_contract WHERE version='hop-duplicate-proposal-v1'
  AND schema=$schema${"type":"object","properties":{"schema_version":{"type":"string","minLength":1,"maxLength":8000,"enum":["hop-duplicate-proposal-v1"]},"release_id":{"type":"string","minLength":1,"maxLength":8000},"cluster_id":{"type":"string","minLength":1,"maxLength":8000},"parent_id":{"type":["string","null"],"minLength":1,"maxLength":8000},"member_ids":{"type":"array","minItems":2,"maxItems":1000,"items":{"type":"string","minLength":1,"maxLength":8000}},"source_binding_hash":{"type":"string","minLength":1,"maxLength":8000},"actor":{"type":"string","minLength":1,"maxLength":8000},"actor_kind":{"type":"string","minLength":1,"maxLength":8000,"enum":["human","assistant"]},"method":{"type":"string","minLength":1,"maxLength":8000,"enum":["MANUAL","MODEL_INFERRED"]},"model_id":{"type":["string","null"],"minLength":1,"maxLength":8000},"prompt_version":{"type":["string","null"],"minLength":1,"maxLength":8000},"resolver_version":{"type":"string","minLength":1,"maxLength":8000},"reason":{"type":"string","minLength":1,"maxLength":8000}},"required":["schema_version","release_id","cluster_id","parent_id","member_ids","source_binding_hash","actor","actor_kind","method","model_id","prompt_version","resolver_version","reason"],"additionalProperties":false}$schema$::jsonb AND content_hash=ontology.hash(schema))
 THEN RAISE EXCEPTION 'DUPLICATE_CONTRACT_CHANGED'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='ontology.duplicate_contract'::regclass AND tgname='ontology_duplicate_contract_immutable') THEN
  CREATE TRIGGER ontology_duplicate_contract_immutable BEFORE UPDATE OR DELETE ON ontology.duplicate_contract
  FOR EACH ROW EXECUTE FUNCTION ontology.immutable();
 END IF;
END $$;
COMMIT;
