-- Generated immutable interpretation contract; no model prompt is changed.
BEGIN;
CREATE TABLE IF NOT EXISTS enrichment.rule_contract (
 schema_version text PRIMARY KEY, output_schema jsonb NOT NULL, content_hash text NOT NULL
);
INSERT INTO enrichment.rule_contract VALUES('guarded-rules-v1',$schema${"type":"object","properties":{"schema_version":{"type":"string","enum":["guarded-rules-v1"]},"rules":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string","minLength":1,"maxLength":40},"action":{"type":"string","enum":["REQUIRE","PERMIT","FORBID","PREFER","UNRESTRICT","LIMIT","DISABLE"]},"statement_parts":{"type":"array","items":{"type":"string","minLength":1,"maxLength":8000},"minItems":1,"maxItems":40},"evidence_ids":{"type":"array","items":{"type":"string","minLength":1,"maxLength":100},"minItems":1,"maxItems":100},"guard":{"anyOf":[{"$ref":"#/$defs/predicate"},{"type":"null"}]},"target_rule_id":{"type":["string","null"],"minLength":1,"maxLength":40}},"required":["id","action","statement_parts","evidence_ids","guard","target_rule_id"],"additionalProperties":false},"minItems":1,"maxItems":100}},"required":["schema_version","rules"],"additionalProperties":false,"$defs":{"predicate":{"type":"object","properties":{"op":{"type":"string","enum":["atom","all_of","any_of","not"]},"parts":{"type":"array","items":{"type":"string","minLength":1,"maxLength":8000},"minItems":0,"maxItems":20},"children":{"type":"array","items":{"$ref":"#/$defs/predicate"},"minItems":0,"maxItems":60}},"required":["op","parts","children"],"additionalProperties":false}},"description":"Explicit normative rules, not a complete applicant-eligibility decision. REQUIRE states a necessary condition. PERMIT allows the stated action when its guard holds and never waives unrelated requirements. FORBID prohibits the stated action or condition. PREFER grants the stated preference. UNRESTRICT states lack of a restriction. LIMIT qualifies its referenced PREFER rule. DISABLE makes its referenced rule nonoperative when active. Every rule is active only when its guard is true and no active DISABLE rule targets it; missing observations retain UNKNOWN. A null guard is unconditional within the original requirement position scope. Predicate atoms are source-text propositions, not model-assigned truth values."}$schema$::jsonb,'e9b849fe15ac15d88e4dfbafa19b9776967a8c36a5cecba7fe3778d4e0dd5a6b') ON CONFLICT DO NOTHING;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM enrichment.rule_contract WHERE schema_version='guarded-rules-v1' AND content_hash='e9b849fe15ac15d88e4dfbafa19b9776967a8c36a5cecba7fe3778d4e0dd5a6b')
 THEN RAISE EXCEPTION 'RULE_CONTRACT_IS_IMMUTABLE'; END IF; END $$;
COMMIT;
